sudo: required
services:
  - docker

before_install:
  - docker build -t gerardolenski/dockerized-react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true gerardolenski/dockerized-react-app npm run test